### ISSUE TITLE
Crash on "NSUInteger cursorPositionInSpacelessString = *cursorPosition;"

### ISSUE THREAD

**Issue by huangwangxin** [chebur/CHRTextFieldFormatter#2]
I use swift and use cardNumberFormatter.maskedStringFromString(text)，but it crash on "NSUInteger cursorPositionInSpacelessString = *cursorPosition;" , the code in CHRCardNumberMask.m file line 49.
What should I do? Forgive my English is very poor.

**Comment by nesterenkodm** [comment]
Will fix it soon. Thank you for your report.

**Comment by huangwangxin** [comment]
Yes, but not modified using Cocoapod.  You need to update the version number with Cocoapod?

**Comment by nesterenkodm** [comment]
version 1.0.1 pushed
